### ISSUE TITLE
code not showing ferris wheel anymore in example

### ISSUE THREAD

**Issue by treeternity** [rbejar/StreetView3DOverlay#2]
hi @rbejar  - looks like its not showing the ferris wheel anymore, sadly 

http://rbejar.github.io/3DMappingExperiments/WebGLTests/StreetViewOverlay_EINA.html

i thought i would post a new issue - cool idea though.

i am trying to volunteer on a fun app to place trees (3d models) anywhere at http://tree.to - if this could work somehow it would be amazing and kudos to you with maybe a link back to your project :)

**Comment by rbejar** [comment]
Now it is working again (see this commit: 5cadc9a0746a3bc37bea6ece8d43288c0e41f3f1). I am loading the model with a 3ds loader instead of converting it before to a three.js format. I have also fixed a few other issues. The positioning looks like it is a little worse than before, but it is, as it was, just a hack.

**Comment by treeternity** [comment]
hey!! you are awesome :) I hope millions of trees are planted in your honor on www.tree.to (expect a link back to your github repo and maybe I can contribute a design for something like streetviewinsert.io :)

**Comment by treeternity** [comment]
if you make this into a more formal API, I bet Google would pick it up and you never know, maybe acquire it :)

**Comment by treeternity** [comment]
It kind of works, my tree is sideways for some reason :)

http://www.tree.to/?

I also added the attribution link but shall make a more formal .html page soon.  And very soon hooking this up to CouchDB to store the trees.  You are awesome :)

If you know why the tree is sideways, and if you can disable the scrolling effects so that the tree stays still, and if you can add the tree by "click" into the "pano" div id, I shall add you as an "author" to the project and you can add this to your resume.

Thanks,
tree.to (eventually you can tell your friends, I just planted a tree for you at tree.to/your-address)

**Comment by treeternity** [comment]
Here is the code: https://github.com/treeternity/treeternity

I just fixed the tree making it stand -- :)

Thanks,
tree.to/
